cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
script: ./build.sh

after_success:
  - echo "after_success"
  #- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ./deploy/public-key.asc.gpg -out ./deploy/public-key.asc -d
  #- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ./deploy/private-key.gpg.gpg -out ./deploy/private-key.gpg -d
  - gpg -d -o ./deploy/public-key.asc --passphrase $ENCRYPTION_PASSWORD ./deploy/public-key.asc.gpg
  - gpg -d -o ./deploy/private-key.gpg --passphrase $ENCRYPTION_PASSWORD ./deploy/private-key.gpg.gpg
  - ./deploy/publish.sh

notifications:
  slack:
    rooms:
      - agile-irb-bnp:xHsrzcqbdHnQzLVEwrUwva8n#skool-trackntrace
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Auteur: %{author}"
      - "Message: %{message}"