cache:
  directories:
  - $HOME/.m2
language: java
jdk:
- oraclejdk8
script: ./build.sh
notifications:
  slack:
    rooms:
      - agile-irb-bnp:xHsrzcqbdHnQzLVEwrUwva8n#skool-trackntrace
    on_success: change
    on_failure: always
    email: false
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Auteur: %{author}"
      - "Message: %{message}"